---
name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shogo82148/actions-setup-perl@v1
        with:
          install-modules-with: cpanm
          install-modules-args: --skip-satisfied
      - name: make
        run: |
          cpanm . --installdeps --skip-satisfied --with-configure --with-develop
          perl Makefile.PL
          make manifest
          make dist
      - uses: actions/upload-artifact@v7
        with:
          path: Archive-SCS-*.tar.gz

  test:
    needs: dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - '5.42'
          - '5.40'
          - '5.38'
          - '5.36'
          - '5.34'
      fail-fast: false
    steps:
      - uses: actions/download-artifact@v8
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          enable-modules-cache: false
      - name: prereqs
        run: |
          cpanm Archive-SCS-*.tar.gz --installdeps --skip-satisfied --with-configure
      - name: dist test
        run: |
          cpanm -v Archive-SCS-*.tar.gz
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
